mysite/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('add', views.add, name='add'),
    path('post/<int:post_id>', views.post, name='post')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

mysite/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    content = models.TextField()
    date_posted = models.DateTimeField('date_posted', auto_now_add=True)

    def __str__(self):
        return self.title

mysite/blog/forms.py
from django.forms import ModelForm, TextInput
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'subtitle', 'author', 'content']
        widgets = {
            'title': TextInput(),
            'subtitle': TextInput(),
            'author': TextInput(),
        }

mysite/blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm

# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html', context={'posts': posts})

def about(request):
    return render(request, 'blog/about.html')

def add(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/blog')
    else:
        form = PostForm()
        return render(request, 'blog/add.html', context={'form': form})

def post(request, post_id):
    post = Post.objects.get(id= post_id)
    return render(request, 'blog/post.html', context={'post': post})

mysite/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
     <!-- Page Header -->
    <header class="masthead" style="background-image: url(https://fullstack2020fall.s3.us-east-2.amazonaws.com/about-bg.jpg)">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>About Me</h1>
              <span class="subheading">This is what I do.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
        </div>
      </div>
    </div>

  {% endblock %}

mysite/blog/templates/blog/add.html
{% extends "blog/base.html" %}

{% block content %}
     <!-- Page Header -->
    <header class="masthead" style="background-image: url(https://fullstack2020fall.s3.us-east-2.amazonaws.com/about-bg.jpg)">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Add post</h1>
            </div>
          </div>
        </div>
      </div>
    </header>

{% load crispy_forms_tags %}
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form action="/blog/add" method="post">
          {% csrf_token %}
          {{ form | crispy }}
          <input type="submit" value="Add" />
        </form>
      </div>
    </div>
  </div>
</article>
{% endblock %}

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My Tech Blog</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="https://fullstack2020fall.s3.us-east-2.amazonaws.com/clean-blog.min.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Anthea's Tech Blog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:add' %}">Add</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


  </body>

</html>

mysite/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url(https://fullstack2020fall.s3.us-east-2.amazonaws.com/about-bg.jpg)">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Welcome to My Tech Blog</h1>
              <span class="subheading"></span>This is where I write random stuff, enjoy</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts %}
          <div class="post-preview">
            <a href="{% url 'blog:post' post.id %}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ post.subtitle }}
              </h3>
            </a>
            <p class="post-meta">Posted by {{ post.author }} on {{ post.date_posted | date:'Y-m-d'}}</p>
          </div>
          {% endfor %}
          <hr>
        </div>
      </div>
    </div> 

{% endblock %}

mysite/blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url(https://fullstack2020fall.s3.us-east-2.amazonaws.com/post-bg.jpg)">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <h2 class="subheading">{{ post.subtitle }}</h2>
              <span class="meta">Posted by
                {{ post.author }}
                on {{ post.date_posted|date:'Y-m-d' }}</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.content|safe }}
          </div>
        </div>
      </div>
    </article>
{% endblock%}